Repository sakshamv30/GetSetFOSS_ML, pull requests merged in 2019-11, with the labels that each got.

#11 Solution for transpose
  Transpose.ipynb
  transpose.PNG
Labels: Easy, getsetfoss2019

#18 Issue #1
  Pandas/getsetfoss_pandas.ipynb
Labels: Medium, getsetfoss2019

#15 Branch1.3
  Untitled.ipynb
  issue 6 soln.ipynb
Labels: getsetfoss2019, very easy

#20 Solution for mathematical operations
  Arithmathic Operations.PNG
  mathematical operations .ipynb
Labels: getsetfoss2019, very easy

#28 issue#6
  python.ipynb
Labels: getsetfoss2019, very easy

#41 worked on issue #4
  mathematical operation.ipynb
  mathematical operation1.ipynb
Labels: Everyone, getsetfoss2019, very easy
